# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish -c Release --no-restore
      working-directory: ./LangFileCleaner

    - name: Compress Build Files
      run: zip -9 -r ${{ env.OS }}.zip publish
      working-directory: ./LangFileCleaner/bin/Release/net9.0
      env:
        OS: ${{ matrix.os }}

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LANGFILECLEANERTOKEN }}
      with:
        tag_name: ${{ github.ref_name }}.${{ github.sha }}
        release_name: Auto-Publish
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        OS: ${{ matrix.os }}
        GITHUB_TOKEN: ${{ secrets.LANGFILECLEANERTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LangFileCleaner/bin/Release/net9.0/${{ env.OS }}.zip
        asset_name: ${{ env.OS }}.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LANGFILECLEANERTOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
